import { Category, Product, Review } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "c1",
    slug: "watches",
    name: "Watches",
    description: "Smart watches built for everyday precision.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "c2",
    slug: "earbuds",
    name: "Earbuds & AirPods",
    description: "True wireless sound, tuned for daily life.",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "c3",
    slug: "chargers",
    name: "Chargers",
    description: "Fast, reliable power for every device.",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "c4",
    slug: "cables",
    name: "Cables",
    description: "Durable cables that outlast the rest.",
    image: "https://images.unsplash.com/photo-1601524909162-ae8725290836?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "c5",
    slug: "accessories",
    name: "Accessories",
    description: "The small details that complete the setup.",
    image: "https://images.unsplash.com/photo-1592890288564-76628a30a657?q=80&w=1200&auto=format&fit=crop",
  },
  {
    id: "c6",
    slug: "gadgets",
    name: "Smart Gadgets",
    description: "Considered tech for a considered life.",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1200&auto=format&fit=crop",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "aeon-watch-one",
    name: "AEON Watch One",
    category: "watches",
    price: 2400,
    discountPrice: 1990,
    description:
      "A minimal smart watch with a sapphire-coated face, seven-day battery life, and full health tracking — built for people who don't want to think about charging.",
    specs: [
      { label: "Display", value: "1.43\" AMOLED" },
      { label: "Battery", value: "Up to 7 days" },
      { label: "Water Resistance", value: "5 ATM" },
      { label: "Connectivity", value: "Bluetooth 5.2" },
    ],
    images: [
      "https://images.unsplash.com/photo-1544117519-31a4b719223d?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=1200&auto=format&fit=crop",
    ],
    inStock: true,
    featured: true,
    isNew: true,
    bestSeller: true,
    rating: 4.8,
    ratingCount: 132,
    views: 0,
    likes: 0,
    createdAt: "2026-06-01",
  },
  {
    id: "p2",
    slug: "aeon-pods-air",
    name: "AEON Pods Air",
    category: "earbuds",
    price: 1450,
    discountPrice: null,
    description:
      "True wireless earbuds with active noise cancellation and a case that fits in the smallest pocket. Tuned for calls, commutes, and everything after.",
    specs: [
      { label: "Battery", value: "8h + 24h case" },
      { label: "ANC", value: "Yes, adaptive" },
      { label: "Charging", value: "USB-C + Wireless" },
      { label: "Water Resistance", value: "IPX4" },
    ],
    images: [
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?q=80&w=1200&auto=format&fit=crop",
    ],
    inStock: true,
    featured: true,
    isNew: false,
    bestSeller: true,
    rating: 4.6,
    ratingCount: 98,
    views: 0,
    likes: 0,
    createdAt: "2026-05-12",
  },
  {
    id: "p3",
    slug: "aeon-charge-30w",
    name: "AEON Charge 30W",
    category: "chargers",
    price: 620,
    discountPrice: 499,
    description:
      "A compact GaN charger that pushes 30W through a single USB-C port — small enough to disappear in a bag, strong enough to matter.",
    specs: [
      { label: "Output", value: "30W USB-C PD" },
      { label: "Build", value: "GaN, compact" },
      { label: "Safety", value: "Over-charge protection" },
    ],
    images: [
      "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=1200&auto=format&fit=crop",
    ],
    inStock: true,
    featured: true,
    isNew: false,
    bestSeller: false,
    rating: 4.7,
    ratingCount: 61,
    views: 0,
    likes: 0,
    createdAt: "2026-04-20",
  },
  {
    id: "p4",
    slug: "aeon-cable-braid",
    name: "AEON Braided Cable",
    category: "cables",
    price: 340,
    discountPrice: 280,
    description:
      "A braided USB-C cable rated for 20,000+ bends. The one cable you stop replacing.",
    specs: [
      { label: "Length", value: "1.2m" },
      { label: "Rating", value: "20,000 bend cycles" },
      { label: "Connector", value: "USB-C to USB-C / Lightning" },
    ],
    images: [
      "https://images.unsplash.com/photo-1601524909162-ae8725290836?q=80&w=1200&auto=format&fit=crop",
    ],
    inStock: true,
    featured: false,
    isNew: true,
    bestSeller: true,
    rating: 4.9,
    ratingCount: 210,
    views: 0,
    likes: 0,
    createdAt: "2026-06-20",
  },
  {
    id: "p5",
    slug: "aeon-mount-mag",
    name: "AEON Magnetic Mount",
    category: "accessories",
    price: 520,
    discountPrice: null,
    description: "A magnetic car mount with a locking swivel head — mounts once, holds forever.",
    specs: [
      { label: "Mount type", value: "Magnetic, air vent" },
      { label: "Rotation", value: "360°" },
      { label: "Compatibility", value: "MagSafe & standard" },
    ],
    images: [
      "https://images.unsplash.com/photo-1592890288564-76628a30a657?q=80&w=1200&auto=format&fit=crop",
    ],
    inStock: true,
    featured: false,
    isNew: false,
    bestSeller: false,
    rating: 4.5,
    ratingCount: 44,
    views: 0,
    likes: 0,
    createdAt: "2026-03-15",
  },
  {
    id: "p6",
    slug: "aeon-tracker-tag",
    name: "AEON Tag",
    category: "gadgets",
    price: 780,
    discountPrice: 690,
    description: "A precision finder tag for keys, bags, and anything you refuse to lose again.",
    specs: [
      { label: "Range", value: "Up to 120m" },
      { label: "Battery", value: "1 year, replaceable" },
      { label: "Water Resistance", value: "IP67" },
    ],
    images: [
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1200&auto=format&fit=crop",
    ],
    inStock: true,
    featured: true,
    isNew: true,
    bestSeller: false,
    rating: 4.4,
    ratingCount: 27,
    views: 0,
    likes: 0,
    createdAt: "2026-06-28",
  },
];

export const REVIEWS: Review[] = [
  { id: "r1", author: "Nourhan A.", rating: 5, text: "The watch battery genuinely lasts a week. Ordering on WhatsApp took two minutes.", product: "AEON Watch One" },
  { id: "r2", author: "Omar S.", rating: 5, text: "Cable still feels new after months of daily use. Worth the price.", product: "AEON Braided Cable" },
  { id: "r3", author: "Mariam K.", rating: 4, text: "Earbuds sound great, case is tiny, exactly as described.", product: "AEON Pods Air" },
  { id: "r4", author: "Youssef H.", rating: 5, text: "Fast reply on WhatsApp, delivery in 3 days, packaging was clean.", product: "AEON Charge 30W" },
];
